# Welcome to Jekyll!
#

# Site settings
title: Mlle Lollipop
description: |
  Créations gourmandes <br>
  Confiseries <br>
  Bar à bonbons
owner: Mlle Lollipop # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mllelollipop.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/MlleLollipop
  github: https://github.com/MlleLollipop
  linkedin-square: https://www.linkedin.com/in/mlle-lollipop-92103769
  facebook-official: https://facebook.com/ConfiserieMlleLollipop/
  google-plus-square: https://plus.google.com/u/0/+Mllelollipop
  email: info@mllelollipop.com
  #flickr:
  instagram: https://www.instagram.com/confiseriemllelollipop/
  youtube-square: https://www.youtube.com/channel/UCAZBLJ6Rl19cnDeFqf1M-Cg/videosRl19cnDeFqf1M-Cg
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
